apiVersion: v1
kind: Service
metadata:
  name: spring-random-pod-service
  labels:
    app: spring-random-pod
    version: dev
spec:
  type: ClusterIP
  selector:
    app: spring-random-pod
    version: dev
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 8080

