apiVersion: v1
kind: Service
metadata:
  name: spring-random-pod-service-production
  labels:
    app: spring-random-pod
    version: production
spec:
  type: ClusterIP
  selector:
    app: spring-random-pod
    version: production
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

