apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: api
  name: spring-random-pod-service
  labels:
    app: spring-random-pod
    version: dev
spec:
  type: LoadBalancer
  selector:
    app: spring-random-pod
    version: dev
  ports:
  - port: 80
    name: https
    targetPort: 8080
  externalTrafficPolicy: Local
  

